/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef ISCHARTBOOST_AUTODEFS_H
#define ISCHARTBOOST_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_ISCHARTBOOST_NAME "IsChartboost"
#define S3E_EXT_ISCHARTBOOST_HASH 0x19e0ccba

#endif /* !ISCHARTBOOST_AUTODEFS_H */
