/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EANDROIDMARKETGOOGLEPLAY_AUTODEFS_H
#define S3EANDROIDMARKETGOOGLEPLAY_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_ANDROIDMARKETGOOGLEPLAY_NAME "s3eAndroidMarketGooglePlay"
#define S3E_EXT_ANDROIDMARKETGOOGLEPLAY_HASH 0xbc5a8fe8

#endif /* !S3EANDROIDMARKETGOOGLEPLAY_AUTODEFS_H */
