/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EANDROIDGOOGLEPLAYBILLING_AUTODEFS_H
#define S3EANDROIDGOOGLEPLAYBILLING_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_ANDROIDGOOGLEPLAYBILLING_NAME "s3eAndroidGooglePlayBilling"
#define S3E_EXT_ANDROIDGOOGLEPLAYBILLING_HASH 0xe13464e5

#endif /* !S3EANDROIDGOOGLEPLAYBILLING_AUTODEFS_H */
