/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef LSGAMEANALYTICS_AUTODEFS_H
#define LSGAMEANALYTICS_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_LSGAMEANALYTICS_NAME "lsGameAnalytics"
#define S3E_EXT_LSGAMEANALYTICS_HASH 0xcc367666

#endif /* !LSGAMEANALYTICS_AUTODEFS_H */
