/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "s3eAndroidMarketGooglePlay_autodefs.h"
#include "s3eEdk.h"
#include "s3eAndroidMarketGooglePlay.h"
//Declarations of Init and Term functions
extern s3eResult s3eAndroidMarketGooglePlayInit();
extern void s3eAndroidMarketGooglePlayTerminate();


void s3eAndroidMarketGooglePlayRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[5];
    funcPtrs[0] = (void*)s3eAndroidMarketGooglePlayIsBillingSupported;
    funcPtrs[1] = (void*)s3eAndroidMarketGooglePlayGetItemData;
    funcPtrs[2] = (void*)s3eAndroidMarketGooglePlayPurchaseItem;
    funcPtrs[3] = (void*)s3eAndroidMarketGooglePlayQueryPurchasedItemAmount;
    funcPtrs[4] = (void*)s3eAndroidMarketGooglePlayQueryPurchasedItem;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[5] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("s3eAndroidMarketGooglePlay", funcPtrs, sizeof(funcPtrs), flags, s3eAndroidMarketGooglePlayInit, s3eAndroidMarketGooglePlayTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int s3eAndroidMarketGooglePlayStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&s3eAndroidMarketGooglePlayRegisterExt;
    return 0;
}

int g_s3eAndroidMarketGooglePlayVal = s3eAndroidMarketGooglePlayStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    s3eAndroidMarketGooglePlayRegisterExt();
}
#endif

#endif
